# Generated by Django 5.1.1 on 2024-09-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_id', models.CharField(max_length=20)),
                ('problem_details', models.TextField()),
                ('complain_image', models.ImageField(blank=True, null=True, upload_to='complain_images/')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_image', models.ImageField(blank=True, null=True, upload_to='resolved_images/')),
                ('solution_details', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
