# Generated by Django 5.1.1 on 2024-10-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Survey', '0002_complain_feedback_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='invoice_image',
            field=models.ImageField(blank=True, null=True, upload_to='invoice_images/'),
        ),
        migrations.AddField(
            model_name='complain',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complain',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
