# Generated by Django 5.1.1 on 2024-10-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Survey', '0005_alter_complain_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='category',
            field=models.CharField(choices=[('Foreign Material', 'Foreign Material'), ('Personal Hygiene', 'Personal Hygiene'), ('Food Quality', 'Food Quality'), ('Others', 'Others')], max_length=20),
        ),
    ]
